name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
        
    - name: Cache SBT dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/build.properties', '**/project/plugins.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
          
    - name: Compile
      run: sbt compile
      
    - name: Run tests
      run: sbt test
      
    - name: Build JAR
      run: sbt assembly
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/test-reports/
        
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: price-basket-jar
        path: target/scala-*/price-basket.jar